name: Build and Deploy NodeJS App on AWS
on:
  push:
    branches:
    - main
  
jobs:
  Build-App:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4    
      - name: barani
        run:
         echo "Hello World"
      - name: barani1
        run:
         echo "Hello World"
      - name: barani2
        run:
         echo "Hello World"
